### ISSUE TITLE
correspondences

### ISSUE THREAD

**Issue by legoc1986** [riccardomarin/Diff-FMaps#5]
Hi
   Thanks for the code of this interesting paper. I am interesting to know how to calculate the correspondences between two point clouds X and Y. As indicate in the paper, Fig1, step c) and d).  Would you tell me where to find these steps in the project and please also share some visualization scripts , that will help  a lot .
Best regards
Xiaofang

**Comment by mrakotosaon** [comment]
Hi @legoc1986
 
You can compute the correspondences by running the script evaluation.m in the evaluation directory. That script should also help creating visualizations.

Best,
Marie-Julie
