### ISSUE TITLE
Hello, how can I get a nice picture like the one in your paper?

### ISSUE THREAD

**Issue by njnj0314** [riccardomarin/Diff-FMaps#8]
How can I get a beautiful visualization like figure 3 in your paper? I only got a graph of the curves.
thanks!

**Comment by riccardomarin** [comment]
Hi @njnj0314 , sorry for the late reply; I suggest this repository that is easy to use and provides really nice renderings:
https://github.com/HTDerekLiu/BlenderToolbox
